### ISSUE TITLE
Pages Format

### ISSUE THREAD

**Issue by itzsaga** [kwelch/react-codeworking-site#3]
Currently weighing between markdown and jsx. So would this just be for content and the layout is still jsx @kwelch? I haven't played with this yet to compare/contrast.

**Comment by kwelch** [comment]
I find writing the pages in markdown to be easier especially since I can write them in Notion and copy them out to markdown. 

However the design flexibility is limited, without additional coding. 

I want to find the balance between these, because I don't want to spend so much time tweaking how the page works that I never get to adding real content. 

Also, I like the idea of have an endless scrolling homepage that is actually route changing as you scroll. 

**Example**
```
------------------------------------------
|                  Header                |
------------------------------------------
# Intro <Route path="/" />
...words
# CoC
...code <Route path="/coc" />
# Why attend
...cool reasons <Route path="/why-attend" />
# Why host
...cooler reasons <Route path="/why-host" />
# Next Event
...cool reasons <Route path="/next" />
------------------------------------------
|                  footer                |
------------------------------------------
```

**Comment by kwelch** [comment]
For now, lets stick with JSX. If we run into any issues with that or we want to allow for markdown for any reason we can add it in the future.
