### ISSUE TITLE
Domain Name

### ISSUE THREAD

**Issue by itzsaga** [kwelch/react-codeworking-site#4]
codeworking.io is available. I could see the codeworking idea growing outside the React community or pivoting if React ever isn't popular anymore (🤞 that's not for a LONG time). Language or location specific slugs could be used if the idea grows e.g. `codeworking.io/nashville/react` etc...

Thoughts?

**Comment by kwelch** [comment]
I absolutely love this idea. This also matches my long term vision for this. 

More notes to come on why (to this point it has been react focused).

**Comment by kwelch** [comment]
The react focus has been due to it being a small enough area that the people using it are running into similar problems. It is also due to how new it is and many of the problems we run into are not really documented well or have consistent solutions. 

I do absolutely think this could be re-branded for other frameworks/technologies with the same constraints.

**Comment by kwelch** [comment]
I have purchased codeworking.io and have the DNS set to go through Netlify
